### ISSUE TITLE
Finish glossary page

### ISSUE THREAD

**Issue by svlem** [svlem/github-for-web-designers#1]
Jani, can you please finish the glossary.html page? It needs terms and definitions. Thanks

**Comment by janilane** [comment]
Yup, I'll get working on this tonight.

**Comment by svlem** [comment]
Thanks Jani, I appreciate the hard work!

**Comment by janilane** [comment]
Sorry to reopen this, I'll be able to do some of it tonight, but I won't be done til Friday.

**Comment by svlem** [comment]
That's okay, thanks again.
